In [81]:
import pandas as pd

In [82]:
df=pd.read_csv("dataset/cust_data.csv")
df

invoice_no customer_id  gender  age         category  quantity    price  \
0        I138884     C241288  Female   28         Clothing         5  1500.40   
1        I317333     C111565    Male   21            Shoes         3  1800.51   
2        I127801     C266599    Male   20         Clothing         1   300.08   
3        I173702     C988172  Female   66            Shoes         5  3000.85   
4        I337046     C189076  Female   53            Books         4    60.60   
...          ...         ...     ...  ...              ...       ...      ...   
99452    I219422     C441542  Female   45         Souvenir         5    58.65   
99453    I325143     C569580    Male   27  Food & Beverage         2    10.46   
99454    I824010     C103292    Male   63  Food & Beverage         2    10.46   
99455    I702964     C800631    Male   56       Technology         4  4200.00   
99456    I232867     C273973  Female   36         Souvenir         3    35.19   

      payment_method invoice_date     shopping_mall  
0        Credit Card     5/8/2022            Kanyon  
1         Debit Card   12/12/2021    Forum Istanbul  
2               Cash    9/11/2021         Metrocity  
3        Credit Card   16/05/2021      Metropol AVM  
4               Cash   24/10/2021            Kanyon  
...              ...          ...               ...  
99452    Credit Card   21/09/2022            Kanyon  
99453           Cash   22/09/2021    Forum Istanbul  
99454     Debit Card   28/03/2021         Metrocity  
99455           Cash   16/03/2021      Istinye Park  
99456    Credit Card   15/10/2022  Mall of Istanbul  

[99457 rows x 10 columns]

In [83]:
x=df.loc[:,:'invoice_no'].values
x

array([['I138884'],
       ['I317333'],
       ['I127801'],
       ...,
       ['I824010'],
       ['I702964'],
       ['I232867']], dtype=object)

In [84]:
df.iloc[:,:-1]


invoice_no customer_id  gender  age         category  quantity    price  \
0        I138884     C241288  Female   28         Clothing         5  1500.40   
1        I317333     C111565    Male   21            Shoes         3  1800.51   
2        I127801     C266599    Male   20         Clothing         1   300.08   
3        I173702     C988172  Female   66            Shoes         5  3000.85   
4        I337046     C189076  Female   53            Books         4    60.60   
...          ...         ...     ...  ...              ...       ...      ...   
99452    I219422     C441542  Female   45         Souvenir         5    58.65   
99453    I325143     C569580    Male   27  Food & Beverage         2    10.46   
99454    I824010     C103292    Male   63  Food & Beverage         2    10.46   
99455    I702964     C800631    Male   56       Technology         4  4200.00   
99456    I232867     C273973  Female   36         Souvenir         3    35.19   

      payment_method invoice_date  
0        Credit Card     5/8/2022  
1         Debit Card   12/12/2021  
2               Cash    9/11/2021  
3        Credit Card   16/05/2021  
4               Cash   24/10/2021  
...              ...          ...  
99452    Credit Card   21/09/2022  
99453           Cash   22/09/2021  
99454     Debit Card   28/03/2021  
99455           Cash   16/03/2021  
99456    Credit Card   15/10/2022  

[99457 rows x 9 columns]

In [85]:
y=df.iloc[:,3].values
df.iloc[:,3]

0        28
1        21
2        20
3        66
4        53
         ..
99452    45
99453    27
99454    63
99455    56
99456    36
Name: age, Length: 99457, dtype: int64

In [86]:
df.head()

invoice_no customer_id  gender  age  category  quantity    price  \
0    I138884     C241288  Female   28  Clothing         5  1500.40   
1    I317333     C111565    Male   21     Shoes         3  1800.51   
2    I127801     C266599    Male   20  Clothing         1   300.08   
3    I173702     C988172  Female   66     Shoes         5  3000.85   
4    I337046     C189076  Female   53     Books         4    60.60   

  payment_method invoice_date   shopping_mall  
0    Credit Card     5/8/2022          Kanyon  
1     Debit Card   12/12/2021  Forum Istanbul  
2           Cash    9/11/2021       Metrocity  
3    Credit Card   16/05/2021    Metropol AVM  
4           Cash   24/10/2021          Kanyon

In [87]:
df.tail()

invoice_no customer_id  gender  age         category  quantity    price  \
99452    I219422     C441542  Female   45         Souvenir         5    58.65   
99453    I325143     C569580    Male   27  Food & Beverage         2    10.46   
99454    I824010     C103292    Male   63  Food & Beverage         2    10.46   
99455    I702964     C800631    Male   56       Technology         4  4200.00   
99456    I232867     C273973  Female   36         Souvenir         3    35.19   

      payment_method invoice_date     shopping_mall  
99452    Credit Card   21/09/2022            Kanyon  
99453           Cash   22/09/2021    Forum Istanbul  
99454     Debit Card   28/03/2021         Metrocity  
99455           Cash   16/03/2021      Istinye Park  
99456    Credit Card   15/10/2022  Mall of Istanbul

In [88]:
from sklearn.preprocessing import LabelEncoder

In [89]:
le_x=LabelEncoder()

In [90]:
x[:,0]=le_x.fit_transform(x[:,0])

In [91]:
x

array([[12165],
       [67813],
       [8722],
       ...,
       [93050],
       [88554],
       [41383]], dtype=object)

In [92]:
from sklearn.preprocessing import OneHotEncoder

In [93]:
ohe=OneHotEncoder()
ohe.fit_transform(df.price.values.reshape(-1,1)).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [94]:
label_encode_y=LabelEncoder()
y=label_encode_y.fit_transform(y)

In [95]:
y

array([10,  3,  2, ..., 45, 38, 18])

In [96]:
from sklearn.model_selection import train_test_split

In [97]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [98]:
x_train

array([[17725],
       [64688],
       [98620],
       ...,
       [13110],
       [19443],
       [41423]], dtype=object)

In [99]:
y_train

array([41, 38,  5, ...,  4, 36, 38])

In [100]:
x_test

array([[54623],
       [91460],
       [74800],
       ...,
       [61831],
       [1419],
       [42920]], dtype=object)

In [101]:
y_test

array([43,  2, 19, ..., 30, 16, 42])

In [102]:
from sklearn.preprocessing import StandardScaler


In [103]:
sc_x=StandardScaler()

In [104]:
x_train_scale=sc_x.fit_transform(x_train[::1])

In [105]:
x_test_scale=sc_x.fit_transform(x_test)

In [106]:
x_train_scale

array([[-1.11584676],
       [ 0.5207378 ],
       [ 1.70321309],
       ...,
       [-1.27667204],
       [-1.05597724],
       [-0.29000981]])

In [107]:
x_test_scale

array([[ 0.17250817],
       [ 1.45287394],
       [ 0.8738123 ],
       ...,
       [ 0.42304096],
       [-1.67673528],
       [-0.23426005]])